### ISSUE TITLE
Session Middleware

### ISSUE THREAD

**Issue by neilscheuermann** [premium-cat-treats/premium-cat-treats#15]
* "As a user, I want to be able to log in so that I can review previous orders."

**Comment by glebec** [comment]
I might state this more as:

> "As a user, I want to have the ability to log in so that _______."

Note how this user story reveals that it's not clear why you actually need login. The motivation for logging in will dictate whether you actually need or want sessions, which are an implementation detail.

**Comment by glebec** [comment]
Also, this codebase already has session middleware:

https://github.com/premium-cat-treats/premium-cat-treats/blob/10dd51a1b383e27ca52d7fb24c4b9c0640e91bec/server/index.js#L55-L62

Do you mean something else?
